version: "3.8"

services:
  web:
    build:
      context: "."
      dockerfile: Dockerfile
      # SQLX will complain without DATABASE_URL in build args
      args:
        - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres-db
      - redis
    environment:
      - CLOUDBET_API_KEY=${CLOUDBET_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - STARBET_PORT=${STARBET_PORT}
    restart: unless-stopped
    ports:
      - "6969:6969"

  postgres-db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - database-persistence:/var/lib/postgresql/data

  redis:
    image: redis
    command: >
          --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres-db
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_USER: ${POSTGRES_USER}
      ADMINER_DEFAULT_DB: ${POSTGRES_DB}
      ADMINER_DESIGN: hydra
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  database-persistence: