@startuml starbet-live

entity AppUser {
    * id: <<uuid>>
    ---
    * username: text
    * email: text
    * name: text
    * surname: text
    * profile_picture: <<url>>
    * password_hash: text
    * password_salt: text
    * balance: int
    * created_at: <<date>>
    * edited_at: <<date>>
    deleted_at: <<date>>
}

entity GameMatch {
    * id: <<uuid>>
    ---
    * game_id: <<FK: Game>>
    ---
    * name_a: text
    * name_b: text
    * starts_at: <<date>>
    * ends_at: <<date>>
    * status: GameMatchStatus
    * created_at: <<date>>
    * edited_at: <<date>>
    deleted_at: <<date>>
}

enum GameMatchStatus {
    PENDING
    LIVE
    FINISHED
    CANCELED
}

entity Game {
    * id: <<uuid>>
    ---
    ' not yet defined
    ' * type: GameType
    * name: text
    * description: text
    * logo: <<url>>
    * genre: Genre
    * created_at: <<date>>
    * edited_at: <<date>>
    deleted_at: <<date>>

}

entity Bet {
    * id: <<uuid>>
    ---
    * app_user_id: <<FK: AppUser>>
    * game_match_id: <<FK: GameMatch>>
    ---
    * amount: int
    * created_at: <<date>>
    * edited_at: <<date>>
    deleted_at: <<date>>
}

entity Odds {
    * id: <<uuid>>
    ---
    * game_match_id: <<FK: GameMatch>>
    ---
    * odds_a: float
    * odds_b: float
    * created_at: <<date>>
    * edited_at: <<date>>
    deleted_at: <<date>>
}

entity MoneyTransaction {
    * id: <<uuid>>
    ---
    * app_user_id: <<FK: AppUser>>
    ---
    * status: MoneyTransactionStatus
    * amount_tokens: int
    * amount_currency: float
    * currency: Currency
    * deposit: bool
    * created_at: <<date>>
    deleted_at: <<date>>
}

enum MoneyTransactionStatus {
    PENDING
    COMPLETED
    CANCELED
}

enum Currency {
    CZK
    EUR
    USD
}

enum Genre {
    MOBA
    FPS
}

GameMatch }o--|| Game
GameMatch ||--o{ Bet
GameMatch ||--o{ Odds
AppUser ||--o{ Bet
AppUser ||--o{ MoneyTransaction
GameMatch -- GameMatchStatus
Game -- Genre
MoneyTransaction -- Currency

@enduml