on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed

name: Deploy

env:
  SQLX_OFFLINE: true

jobs:
  production:
    runs-on:
      - self-hosted
      - baremetal
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: docker compose up --detach --build --wait --wait-timeout 30
        env:
          CLOUDBET_API_KEY: ${{ secrets.CLOUDBET_API_KEY }}
          STARBET_PORT: ${{ vars.STARBET_PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
