on:
  pull_request:
  push:
    branches:
      - main

name: CI

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted
      - docker
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-Awarnings"
      - name: Build
        run: cargo build --verbose
  test:
    name: Test
    runs-on:
      - self-hosted
      - docker
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-Awarnings"
      - name: Test
        run: cargo test --verbose
