on: pull_request

name: Code quality

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Cargo fmt suggestions
    runs-on:
      - self-hosted
      - docker
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
          args: --all
          commit-message: "Format code with rustfmt"
  clippy:
    name: Clippy warnings
    runs-on:
      - self-hosted
      - docker
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
          name: Display clippy warnings in GitHub
